### PR TITLE
1.13 support

### PR DESCRIPTION
**Pull request by ghost**
- Switched to Gradle instead of Maven (personal preference, and it's faster than Maven)
- Modified the Player wrapper and Console wrapper for adding the new 1.13+ Player/Console methods
- Modified all the things who need to be called sync (Player#sendMessage, Server#dispatchCommand etc..)
- Modified some minor things in the code (removed unnecessary server field in main class and use Bukkit#getServer instead)

I don't have tested the plugin (I've just started it on my test server and it launched without problem)

### CODE REVIEW

**Comment by ghost** [comment]
I've also updated all the dependencies and they are shaded using shadow gradle plugin

**Comment by uncovery** [comment]
Now Maven does not work anymore. 
Also, this does not work as a gradle plugin on Netbeans.

**Comment by uncovery** [comment]
When I load this in netbeans, I think there is some confusion if this is a gradle or Maven project. Could it be that there are some leftovers in the code that designate it as a Maven project?

**Comment by ghost** [comment]
You can Download the gradle plugin for netbeans on netbeans Website or just remove the gradle files and put back your pom.xml file

**Comment by uncovery** [comment]
nevermind, had to re-clone it, now it seems to work. Just have to find out now how to add the spigot api dependency,

**Comment by ghost** [comment]
If you keep using Maven: https://www.spigotmc.org/wiki/spigot-maven/ but if you use Gradle, spigot dependency is already in the build.gradle

**Comment by uncovery** [comment]
yes, thanks I have seen that, but where to place the file? into .gradle directory?

**Comment by ghost** [comment]
At the root of your project

**Comment by uncovery** [comment]
ah I get what is wrong, you are makeing spigot a dependency, I am using spigot-api.

**Comment by uncovery** [comment]
hmmm I got it to resolve all the dependencies, but none of them are included in the .jar
all the http-... files need to be in the jar, any idea how to fix that?

**Comment by ghost** [comment]
If you are using my build.gradle file, you have a gradle task named shadowJar, it will create a shaded jar will all the dependancy

**Pull request merged**
